name: flutter_mpgs_sdk
description: Flutter Package for Directpay
version: 0.0.1
author: directpay.lk
homepage: directpay.lk

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^1.0.6
  flutter_webview_plugin: ^0.3.11
  provider: ^4.3.2+2
  flip_card: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.paymedia.flutter_mpgs_sdk
    pluginClass: FlutterMpgsSdkPlugin
  # To add assets to your plugin package, add an assets section, like this:

  fonts:
    - family: U and I
      fonts:
        - asset: packages/flutter_mpgs_sdk/assets/fonts/fontYouandiModernTR.ttf
    - family: Satisfy
      fonts:
        - asset: packages/flutter_mpgs_sdk/assets/fonts/Satisfy-Regular.ttf

  assets:
   - packages/flutter_mpgs_sdk/assets/images/success.png
   - packages/flutter_mpgs_sdk/assets/images/cancel.png
   - packages/flutter_mpgs_sdk/assets/images/master.png
   - packages/flutter_mpgs_sdk/assets/images/visa.png
   - packages/flutter_mpgs_sdk/assets/images/directpay_full.png
   - packages/flutter_mpgs_sdk/assets/images/directpay.png
   - packages/flutter_mpgs_sdk/assets/images/amex.png
   - packages/flutter_mpgs_sdk/assets/images/checkmark.png
   - packages/flutter_mpgs_sdk/assets/images/discover.png
   - packages/flutter_mpgs_sdk/assets/images/mastercard.png
   - packages/flutter_mpgs_sdk/assets/images/others.png
   - packages/flutter_mpgs_sdk/assets/images/visacard.png

  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#   fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
